### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by Kale-Ko**
Tested pretty quickly on fabric-1.14.8-1.19, everything seems to work.

### CODE REVIEW

**Comment by DarkKronicle** [comment]
Thanks!

Any reason you ended up removing FluidText/RawText?

**Comment by Kale-Ko** [comment]
With the update to the text system there is no way to extend MutableText anymore and the whole class seemed a bit unnecessary to begin with

**Comment by Kale-Ko** [comment]
It should be all good to merge now

**Comment by Kale-Ko** [comment]
It should be all good to merge now

**Comment by Kale-Ko** [comment]
Scratch that, something appears to be wrong with the MixinMinecraftClient#openChatScreen mixin

**Comment by DarkKronicle** [comment]
I'll take a look at it

**Pull request merged**
